<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\SarilarTrafficFine.Business\SarilarTrafficFine.Business.csproj" />
		<ProjectReference Include="..\SarilarTrafficFine.DataAccess\SarilarTrafficFine.DataAccess.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="QuestPDF" Version="2026.7.3" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>b5b50f5d-42d9-4dad-86aa-cf32e6ba3ff7</UserSecretsId>
	</PropertyGroup>

</Project>